### ISSUE TITLE
Вопрос по Spring Security Java Config

### ISSUE THREAD

**Issue by yeryomenkom** [elennaro/sshwa#2]
Здраствуйте!

Не поможете мне с конфигом для REST сервиса?
Напишите мне пожалуйста https://vk.com/id56618358

**Comment by elennaro** [comment]
Unfortunately I don't use Vkontakte.
Try to post your question to http://stackoverflow.com, I'd be glad to try to help you :)

**Comment by yeryomenkom** [comment]
Thank you for your time. Here is my question:
https://stackoverflow.com/questions/32424154/spring-security-rest-java-confiigs-base-auth
